// <auto-generated />
using System;
using AutoWeighbridgeSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutoWeighbridgeSystem.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AutoWeighbridgeSystem.Models.Customer", b =>
                {
                    b.Property<string>("CustomerId")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = "KVL",
                            CustomerName = "Khách vãng lai",
                            IsDeleted = false
                        },
                        new
                        {
                            CustomerId = "MX1",
                            CustomerName = "Máy xay 1",
                            IsDeleted = false
                        },
                        new
                        {
                            CustomerId = "MX2",
                            CustomerName = "Máy xay 2",
                            IsDeleted = false
                        },
                        new
                        {
                            CustomerId = "MX3",
                            CustomerName = "Máy xay 3",
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("AutoWeighbridgeSystem.Models.Product", b =>
                {
                    b.Property<string>("ProductId")
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("varchar(8)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = "XOBO",
                            IsDeleted = false,
                            ProductName = "Đá xô bồ"
                        });
                });

            modelBuilder.Entity("AutoWeighbridgeSystem.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullName = "Quản trị hệ thống",
                            IsActive = true,
                            Password = "123",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            FullName = "Nhân viên trạm cân",
                            IsActive = true,
                            Password = "123",
                            Role = "Operator",
                            Username = "operator"
                        },
                        new
                        {
                            Id = 3,
                            FullName = "Thanh tra khoáng sản",
                            IsActive = true,
                            Password = "123",
                            Role = "Viewer",
                            Username = "viewer"
                        });
                });

            modelBuilder.Entity("AutoWeighbridgeSystem.Models.Vehicle", b =>
                {
                    b.Property<int>("VehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleId"));

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(8)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("RfidCardId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("TareWeight")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("VehicleId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("LicensePlate");

                    b.HasIndex("RfidCardId")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0 AND [RfidCardId] IS NOT NULL");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            VehicleId = 1,
                            CustomerId = "MX1",
                            IsDeleted = false,
                            LicensePlate = "86C-12345",
                            RfidCardId = "1234",
                            TareWeight = 12500m
                        });
                });

            modelBuilder.Entity("AutoWeighbridgeSystem.Models.WeighingTicket", b =>
                {
                    b.Property<string>("TicketID")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("GrossWeight")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18, 2)");

                    b.Property<bool>("IsVoid")
                        .HasColumnType("bit");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("NetWeight")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TareWeight")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("TimeIn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TimeOut")
                        .HasColumnType("datetime2");

                    b.Property<int?>("VehicleId")
                        .HasColumnType("int");

                    b.Property<string>("VoidReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("TicketID");

                    b.HasIndex("TimeIn")
                        .HasDatabaseName("IX_WeighingTickets_TimeIn");

                    b.HasIndex("VehicleId");

                    b.HasIndex("LicensePlate", "IsVoid", "TimeOut")
                        .HasDatabaseName("IX_WeighingTickets_OpenTicketLookup");

                    b.ToTable("WeighingTickets");

                    b.HasData(
                        new
                        {
                            TicketID = "260412-001",
                            CustomerName = "Máy xay 1",
                            GrossWeight = 35400m,
                            IsVoid = false,
                            LicensePlate = "86C-12345",
                            NetWeight = 22900m,
                            ProductName = "Đá xô bồ",
                            TareWeight = 12500m,
                            TimeIn = new DateTime(2026, 4, 16, 11, 3, 29, 777, DateTimeKind.Local).AddTicks(5195),
                            TimeOut = new DateTime(2026, 4, 16, 11, 18, 29, 777, DateTimeKind.Local).AddTicks(5208),
                            VehicleId = 1
                        });
                });

            modelBuilder.Entity("AutoWeighbridgeSystem.Models.Vehicle", b =>
                {
                    b.HasOne("AutoWeighbridgeSystem.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("AutoWeighbridgeSystem.Models.WeighingTicket", b =>
                {
                    b.HasOne("AutoWeighbridgeSystem.Models.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Vehicle");
                });
#pragma warning restore 612, 618
        }
    }
}
